In [1]:
import pandas as pd
import numpy as np
import datetime as d
import matplotlib.pyplot as plt

In [2]:
s = d.datetime(2024,1,1)
e = d.datetime(2024,9,12)

In [3]:
df = pd.read_csv("../DataSets/Nifty_Stocks.csv")
df

Date         Open         High          Low        Close  \
0      2024-01-01  3790.000000  3832.000000  3773.000000  3811.100098   
1      2024-01-02  3811.100098  3811.100098  3767.250000  3783.199951   
2      2024-01-03  3767.000000  3771.850098  3687.050049  3691.750000   
3      2024-01-04  3701.750000  3719.000000  3651.000000  3666.800049   
4      2024-01-05  3675.000000  3747.750000  3674.850098  3737.899902   
...           ...          ...          ...          ...          ...   
10813  2024-09-05   654.000000   684.000000   653.700012   664.500000   
10814  2024-09-06   667.799988   679.849976   657.099976   661.849976   
10815  2024-09-09   665.750000   677.900024   664.000000   672.750000   
10816  2024-09-10   677.000000   684.000000   675.500000   678.900024   
10817  2024-09-11   681.000000   683.000000   674.049988   680.500000   

         Adj Close   Volume Symbol     Category  Daily_Return  Price_Range  \
0      3757.422119   825907    TCS  IT_industry   3711.100098    59.000000   
1      3729.915039  1344068    TCS  IT_industry   3683.199951    43.850098   
2      3639.753174  1803075    TCS  IT_industry   3591.750000    84.800049   
3      3615.154541  3598144    TCS  IT_industry   3566.800049    68.000000   
4      3685.252930  1963127    TCS  IT_industry   3637.899902    72.899902   
...            ...      ...    ...          ...           ...          ...   
10813   664.500000  3457002  RITES     Railways    564.500000    30.299988   
10814   661.849976  1482454  RITES     Railways    561.849976    22.750000   
10815   672.750000  1991325  RITES     Railways    572.750000    13.900024   
10816   678.900024   624747  RITES     Railways    578.900024     8.500000   
10817   680.500000   704295  RITES     Railways    580.500000     8.950012   

        Volatility  Cumulative_Return  Average_Price  
0      3732.999714                NaN    5695.550049  
1      3711.521697          -0.007321    5702.700073  
2      3671.977407          -0.031493    5612.875000  
3      3619.430895          -0.038252    5535.150024  
4      3649.436771          -0.018862    5543.949951  
...            ...                ...            ...  
10813   585.625280          97.873441     986.250000  
10814   580.567661          97.869453     998.724976  
10815   579.200656          97.885922    1002.125000  
10816   584.500814          97.895063    1016.450012  
10817   583.947834          97.897420    1021.250000  

[10818 rows x 14 columns]

In [4]:
df.Symbol.unique()

array(['TCS', 'WIPRO', 'OFSS', 'KPITTECH', 'INFY', 'HCLTECH', 'LTIM',
       'TECHM', 'PERSISTENT', 'MPHASIS', 'TATAELXSI', 'COFORGE', 'CYIENT',
       'AFFLE', 'ZENSERTECH', 'BAYERCROP', 'UPL LIMITED', 'ESCORTS',
       'PIIND', 'BASF', 'JSWENERGY', 'RELIANCE', 'NTPC', 'ONGC',
       'ADANIGREEN', 'APOLLOHOSP', 'ARTEMISMED', 'ASTERDM', 'LALPATHLAB',
       'FORTIS', 'HINDUNILVR', 'ITC', 'NESTLEIND', 'BRITANNIA', 'MARICO',
       'INFOSYS', 'HAL', 'BDL', 'BEL', 'MDL', 'BEML', 'HDFCBank',
       'ICICIBANK', 'BAJFINANCE', 'SBIN', 'AXISBANK', 'IRFC', 'IRCTC',
       'RVNL', 'BHEL', 'TITAGARH', 'KERNEX', 'NCC', 'DCW', 'IRCON',
       'RAILTEL', 'CONCOR', 'RITES'], dtype=object)

In [5]:
df.Date.nunique()

172

In [6]:
df.Symbol.nunique()

58

In [7]:
df.dtypes

Date                  object
Open                 float64
High                 float64
Low                  float64
Close                float64
Adj Close            float64
Volume                 int64
Symbol                object
Category              object
Daily_Return         float64
Price_Range          float64
Volatility           float64
Cumulative_Return    float64
Average_Price        float64
dtype: object

In [8]:
df.isnull().sum()

Date                 0
Open                 0
High                 0
Low                  0
Close                0
Adj Close            0
Volume               0
Symbol               0
Category             0
Daily_Return         0
Price_Range          0
Volatility           0
Cumulative_Return    1
Average_Price        0
dtype: int64

In [9]:
df = df.fillna(0)

In [10]:
df.isnull().sum()

Date                 0
Open                 0
High                 0
Low                  0
Close                0
Adj Close            0
Volume               0
Symbol               0
Category             0
Daily_Return         0
Price_Range          0
Volatility           0
Cumulative_Return    0
Average_Price        0
dtype: int64

In [11]:
df.sort_values( by = ['Symbol','Date'])

Date         Open         High          Low        Close  \
4128  2024-01-01  1598.000000  1620.000000  1585.000000  1598.400024   
4129  2024-01-02  1598.800049  1616.000000  1565.699951  1603.550049   
4130  2024-01-03  1699.000000  1747.400024  1610.000000  1697.250000   
4131  2024-01-04  1706.550049  1723.000000  1675.050049  1692.500000   
4132  2024-01-05  1695.000000  1700.000000  1660.000000  1674.000000   
...          ...          ...          ...          ...          ...   
2575  2024-09-06   798.500000   814.799988   775.000000   778.599976   
2576  2024-09-09   777.750000   777.750000   755.299988   764.450012   
2577  2024-09-10   766.200012   796.099976   766.200012   792.599976   
2578  2024-09-11   793.000000   807.750000   761.450012   766.099976   
2579  2024-09-12   774.000000   778.799988   759.000000   770.400024   

        Adj Close   Volume      Symbol     Category  Daily_Return  \
4128  1598.400024   912757  ADANIGREEN       Energy   1498.400024   
4129  1603.550049  1031651  ADANIGREEN       Energy   1503.550049   
4130  1697.250000  8064214  ADANIGREEN       Energy   1597.250000   
4131  1692.500000  1492988  ADANIGREEN       Energy   1592.500000   
4132  1674.000000   871729  ADANIGREEN       Energy   1574.000000   
...           ...      ...         ...          ...           ...   
2575   778.599976   771824  ZENSERTECH  IT_industry    678.599976   
2576   764.450012   419878  ZENSERTECH  IT_industry    664.450012   
2577   792.599976   445523  ZENSERTECH  IT_industry    692.599976   
2578   766.099976   894510  ZENSERTECH  IT_industry    666.099976   
2579   770.400024   387816  ZENSERTECH  IT_industry    670.400024   

      Price_Range   Volatility  Cumulative_Return  Average_Price  
4128    35.000000  1520.838340          27.097994    2397.200012  
4129    50.300049  1518.360394          27.101216    2400.575073  
4130   137.400024  1652.540693          27.159648    2547.625000  
4131    47.949951  1624.031016          27.156850    2552.800049  
4132    40.000000  1600.836320          27.145919    2532.000000  
...           ...          ...                ...            ...  
2575    39.799988   715.262353          10.698103    1187.799988  
2576    22.450012   678.946942          10.679929    1159.975006  
2577    29.899963   699.430781          10.716753    1162.500000  
2578    46.299988   708.356966          10.683319    1176.049988  
2579    19.799988   680.279742          10.688931    1159.200012  

[10818 rows x 14 columns]

In [12]:
df['Date'] = pd.to_datetime(df['Date'])

In [13]:
df.dtypes

Date                 datetime64[ns]
Open                        float64
High                        float64
Low                         float64
Close                       float64
Adj Close                   float64
Volume                        int64
Symbol                       object
Category                     object
Daily_Return                float64
Price_Range                 float64
Volatility                  float64
Cumulative_Return           float64
Average_Price               float64
dtype: object

In [14]:
df.groupby("Date")["Close"].mean().head(50)

Date
2024-01-01    2052.582781
2024-01-02    2040.473649
2024-01-03    2021.038797
2024-01-04    2032.984357
2024-01-05    2051.697220
2024-01-08    2035.919456
2024-01-09    2043.862702
2024-01-10    2054.565470
2024-01-11    2059.394057
2024-01-12    2097.298028
2024-01-15    2108.172214
2024-01-16    2099.249207
2024-01-17    2094.513110
2024-01-18    2146.899599
2024-01-19    2112.998409
2024-01-23    2066.136126
2024-01-24    2087.793658
2024-01-25    2073.526971
2024-01-29    2090.696417
2024-01-30    2082.763874
2024-01-31    2102.861109
2024-02-01    2100.094439
2024-02-02    2120.262696
2024-02-05    2103.219439
2024-02-06    2130.204744
2024-02-07    2138.375398
2024-02-08    2132.862687
2024-02-09    2127.275403
2024-02-12    2108.208745
2024-02-13    2117.533726
2024-02-14    2122.295638
2024-02-15    2140.801587
2024-02-16    2154.300391
2024-02-19    2165.934109
2024-02-20    2157.484543
2024-02-21    2132.819454
2024-02-22    2154.382948
2024-02-23    2156.459917
2024-02

In [15]:
df['SMA_50'] = df['Close'].rolling(window=50).mean()

In [16]:
df['SMA_200'] = df['Close'].rolling(window=200).mean()

In [17]:
df.SMA_50.unique()

array([          nan, 3962.09203125, 3970.02203125, ...,  694.95400269,
        694.70200317,  694.47700317])

In [18]:
df.dtypes

Date                 datetime64[ns]
Open                        float64
High                        float64
Low                         float64
Close                       float64
Adj Close                   float64
Volume                        int64
Symbol                       object
Category                     object
Daily_Return                float64
Price_Range                 float64
Volatility                  float64
Cumulative_Return           float64
Average_Price               float64
SMA_50                      float64
SMA_200                     float64
dtype: object

In [19]:
df["SMA_50"] = df["SMA_50"].fillna(0)
df["SMA_200"] = df["SMA_200"].fillna(0)

In [20]:
df.SMA_50.unique()

array([   0.        , 3962.09203125, 3970.02203125, ...,  694.95400269,
        694.70200317,  694.47700317])

In [21]:
def calculate_rsi(data, window=50):
    """
    Calculates the Relative Strength Index (RSI) for a given dataset.
    
    :param data: pandas Series of closing prices.
    :param window: The period for RSI calculation (default is 14).
    :return: pandas Series with RSI values.
    """
    # 1. Calculate price changes
    delta = data.diff(1)
    
    # 2. Separate gains and losses
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    
    # 3. Calculate the smoothed average of gains and losses
    # The first value is a simple average, subsequent values are exponentially weighted.
    # com=window-1 is equivalent to alpha=1/window, which is the standard for RSI.
    avg_gain = gain.ewm(com=window - 1, adjust=False).mean()
    avg_loss = loss.ewm(com=window - 1, adjust=False).mean()
    
    # 4. Calculate Relative Strength (RS)
    rs = avg_gain / avg_loss
    
    # 5. Calculate the RSI
    rsi = 100 - (100 / (1 + rs))
    
    return rsi


In [22]:
df['RSI'] = df.groupby('Symbol')['Close'].transform(lambda x: calculate_rsi(x, window=50))

In [23]:
df["RSI"] = df["RSI"].fillna(0)

In [24]:
df.RSI.unique()

array([ 0.        ,  4.75155529,  4.56597998, ..., 49.14638384,
       49.66054661, 49.79529811])

In [25]:
def calculate_macd(data, short_window=12, long_window=26, signal_window=9):
    """
    Calculate MACD (Moving Average Convergence Divergence).
    
    Parameters:
        data          : pandas Series of prices (e.g. closing prices)
        short_window  : EMA short period (default=12)
        long_window   : EMA long period (default=26)
        signal_window : EMA of MACD line (default=9)
        
    Returns:
        macd_line, signal_line, histogram : pandas Series
    """
    # Short-term EMA
    ema_short = data.ewm(span=short_window, adjust=False).mean()
    
    # Long-term EMA
    ema_long = data.ewm(span=long_window, adjust=False).mean()
    
    # MACD Line
    macd_line = ema_short - ema_long
    
    # Signal Line
    signal_line = macd_line.ewm(span=signal_window, adjust=False).mean()
    
    # Histogram
    histogram = macd_line - signal_line
    
    return macd_line, signal_line, histogram



data =df.Close
macd_line, signal_line, histogram = calculate_macd(data)

print("MACD Line:\n", macd_line)
print("\nSignal Line:\n", signal_line)
print("\nHistogram:\n",histogram)

MACD Line:
 0         0.000000
1        -2.225653
2       -11.239187
3       -20.163300
4       -21.253563
           ...    
10813   -11.666384
10814   -10.482616
10815    -8.566186
10816    -6.476488
10817    -4.637821
Name: Close, Length: 10818, dtype: float64

Signal Line:
 0         0.000000
1        -0.445131
2        -2.603942
3        -6.115814
4        -9.143363
           ...    
10813   -13.535340
10814   -12.924795
10815   -12.053073
10816   -10.937756
10817    -9.677769
Name: Close, Length: 10818, dtype: float64

Histogram:
 0         0.000000
1        -1.780522
2        -8.635245
3       -14.047487
4       -12.110199
           ...    
10813     1.868957
10814     2.442179
10815     3.486888
10816     4.461268
10817     5.039948
Name: Close, Length: 10818, dtype: float64


In [26]:
df['MACD12'] = df['Close'].rolling(window=12).mean()
df['MACD26'] = df['Close'].rolling(window=26).mean()
df['MACD9'] = df['Close'].rolling(window=9).mean()

In [27]:
df.MACD12=df.MACD12.fillna(0)
df.MACD26=df.MACD26.fillna(0)
df.MACD9=df.MACD9.fillna(0)

In [28]:
df.isnull().sum()

Date                 0
Open                 0
High                 0
Low                  0
Close                0
Adj Close            0
Volume               0
Symbol               0
Category             0
Daily_Return         0
Price_Range          0
Volatility           0
Cumulative_Return    0
Average_Price        0
SMA_50               0
SMA_200              0
RSI                  0
MACD12               0
MACD26               0
MACD9                0
dtype: int64

In [29]:
# 30-day rolling volatility
df['RollingVolatility'] = df['Close'].rolling(window=30).std() * np.sqrt(252)

print(df[['Close','RollingVolatility']].tail())

            Close  RollingVolatility
10813  664.500000         485.477247
10814  661.849976         487.379388
10815  672.750000         486.737803
10816  678.900024         419.154230
10817  680.500000         342.399928


In [30]:
df['RollingVolatility'] = df['RollingVolatility'].rolling(window=1).mean()
df

Date         Open         High          Low        Close  \
0     2024-01-01  3790.000000  3832.000000  3773.000000  3811.100098   
1     2024-01-02  3811.100098  3811.100098  3767.250000  3783.199951   
2     2024-01-03  3767.000000  3771.850098  3687.050049  3691.750000   
3     2024-01-04  3701.750000  3719.000000  3651.000000  3666.800049   
4     2024-01-05  3675.000000  3747.750000  3674.850098  3737.899902   
...          ...          ...          ...          ...          ...   
10813 2024-09-05   654.000000   684.000000   653.700012   664.500000   
10814 2024-09-06   667.799988   679.849976   657.099976   661.849976   
10815 2024-09-09   665.750000   677.900024   664.000000   672.750000   
10816 2024-09-10   677.000000   684.000000   675.500000   678.900024   
10817 2024-09-11   681.000000   683.000000   674.049988   680.500000   

         Adj Close   Volume Symbol     Category  Daily_Return  ...  \
0      3757.422119   825907    TCS  IT_industry   3711.100098  ...   
1      3729.915039  1344068    TCS  IT_industry   3683.199951  ...   
2      3639.753174  1803075    TCS  IT_industry   3591.750000  ...   
3      3615.154541  3598144    TCS  IT_industry   3566.800049  ...   
4      3685.252930  1963127    TCS  IT_industry   3637.899902  ...   
...            ...      ...    ...          ...           ...  ...   
10813   664.500000  3457002  RITES     Railways    564.500000  ...   
10814   661.849976  1482454  RITES     Railways    561.849976  ...   
10815   672.750000  1991325  RITES     Railways    572.750000  ...   
10816   678.900024   624747  RITES     Railways    578.900024  ...   
10817   680.500000   704295  RITES     Railways    580.500000  ...   

        Volatility  Cumulative_Return  Average_Price      SMA_50     SMA_200  \
0      3732.999714           0.000000    5695.550049    0.000000    0.000000   
1      3711.521697          -0.007321    5702.700073    0.000000    0.000000   
2      3671.977407          -0.031493    5612.875000    0.000000    0.000000   
3      3619.430895          -0.038252    5535.150024    0.000000    0.000000   
4      3649.436771          -0.018862    5543.949951    0.000000    0.000000   
...            ...                ...            ...         ...         ...   
10813   585.625280          97.873441     986.250000  696.013004  730.830251   
10814   580.567661          97.869453     998.724976  695.392003  728.939751   
10815   579.200656          97.885922    1002.125000  694.954003  727.103751   
10816   584.500814          97.895063    1016.450012  694.702003  725.255001   
10817   583.947834          97.897420    1021.250000  694.477003  723.455251   

             RSI      MACD12      MACD26       MACD9  RollingVolatility  
0       0.000000    0.000000    0.000000    0.000000                NaN  
1       0.000000    0.000000    0.000000    0.000000                NaN  
2       0.000000    0.000000    0.000000    0.000000                NaN  
3       0.000000    0.000000    0.000000    0.000000                NaN  
4       4.751555    0.000000    0.000000    0.000000                NaN  
...          ...         ...         ...         ...                ...  
10813  48.436346  654.395844  670.971156  653.800008         485.477247  
10814  48.227915  654.537506  668.923079  655.200005         487.379388  
10815  49.146384  655.870839  667.040386  657.316671         486.737803  
10816  49.660547  658.141673  665.359619  659.644450         419.154230  
10817  49.795298  660.745839  665.096159  662.444451         342.399928  

[10818 rows x 21 columns]

In [31]:
df.RollingVolatility.isnull().sum()

29

In [32]:
df.RollingVolatility = df.RollingVolatility.fillna(0)

In [33]:
df['Daily_volatility'] = df['Close'].rolling(window=1).mean()

In [34]:
df.Daily_volatility.isnull().sum()

0

In [35]:
df.Daily_volatility=df.Daily_volatility.fillna(0)

In [36]:
df['Annual_volatility'] = df['Close'].rolling(window=1).mean()

In [37]:
df.Annual_volatility.isnull().sum()

0

In [38]:
df.Annual_volatility =df.Annual_volatility .fillna(0)

In [39]:
df

Date         Open         High          Low        Close  \
0     2024-01-01  3790.000000  3832.000000  3773.000000  3811.100098   
1     2024-01-02  3811.100098  3811.100098  3767.250000  3783.199951   
2     2024-01-03  3767.000000  3771.850098  3687.050049  3691.750000   
3     2024-01-04  3701.750000  3719.000000  3651.000000  3666.800049   
4     2024-01-05  3675.000000  3747.750000  3674.850098  3737.899902   
...          ...          ...          ...          ...          ...   
10813 2024-09-05   654.000000   684.000000   653.700012   664.500000   
10814 2024-09-06   667.799988   679.849976   657.099976   661.849976   
10815 2024-09-09   665.750000   677.900024   664.000000   672.750000   
10816 2024-09-10   677.000000   684.000000   675.500000   678.900024   
10817 2024-09-11   681.000000   683.000000   674.049988   680.500000   

         Adj Close   Volume Symbol     Category  Daily_Return  ...  \
0      3757.422119   825907    TCS  IT_industry   3711.100098  ...   
1      3729.915039  1344068    TCS  IT_industry   3683.199951  ...   
2      3639.753174  1803075    TCS  IT_industry   3591.750000  ...   
3      3615.154541  3598144    TCS  IT_industry   3566.800049  ...   
4      3685.252930  1963127    TCS  IT_industry   3637.899902  ...   
...            ...      ...    ...          ...           ...  ...   
10813   664.500000  3457002  RITES     Railways    564.500000  ...   
10814   661.849976  1482454  RITES     Railways    561.849976  ...   
10815   672.750000  1991325  RITES     Railways    572.750000  ...   
10816   678.900024   624747  RITES     Railways    578.900024  ...   
10817   680.500000   704295  RITES     Railways    580.500000  ...   

       Average_Price      SMA_50     SMA_200        RSI      MACD12  \
0        5695.550049    0.000000    0.000000   0.000000    0.000000   
1        5702.700073    0.000000    0.000000   0.000000    0.000000   
2        5612.875000    0.000000    0.000000   0.000000    0.000000   
3        5535.150024    0.000000    0.000000   0.000000    0.000000   
4        5543.949951    0.000000    0.000000   4.751555    0.000000   
...              ...         ...         ...        ...         ...   
10813     986.250000  696.013004  730.830251  48.436346  654.395844   
10814     998.724976  695.392003  728.939751  48.227915  654.537506   
10815    1002.125000  694.954003  727.103751  49.146384  655.870839   
10816    1016.450012  694.702003  725.255001  49.660547  658.141673   
10817    1021.250000  694.477003  723.455251  49.795298  660.745839   

           MACD26       MACD9  RollingVolatility  Daily_volatility  \
0        0.000000    0.000000           0.000000       3811.100098   
1        0.000000    0.000000           0.000000       3783.199951   
2        0.000000    0.000000           0.000000       3691.750000   
3        0.000000    0.000000           0.000000       3666.800049   
4        0.000000    0.000000           0.000000       3737.899902   
...           ...         ...                ...               ...   
10813  670.971156  653.800008         485.477247        664.500000   
10814  668.923079  655.200005         487.379388        661.849976   
10815  667.040386  657.316671         486.737803        672.750000   
10816  665.359619  659.644450         419.154230        678.900024   
10817  665.096159  662.444451         342.399928        680.500000   

       Annual_volatility  
0            3811.100098  
1            3783.199951  
2            3691.750000  
3            3666.800049  
4            3737.899902  
...                  ...  
10813         664.500000  
10814         661.849976  
10815         672.750000  
10816         678.900024  
10817         680.500000  

[10818 rows x 23 columns]

In [40]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [41]:
df.dtypes

Date                 datetime64[ns]
Open                        float64
High                        float64
Low                         float64
Close                       float64
Adj Close                   float64
Volume                        int64
Symbol                       object
Category                     object
Daily_Return                float64
Price_Range                 float64
Volatility                  float64
Cumulative_Return           float64
Average_Price               float64
SMA_50                      float64
SMA_200                     float64
RSI                         float64
MACD12                      float64
MACD26                      float64
MACD9                       float64
RollingVolatility           float64
Daily_volatility            float64
Annual_volatility           float64
dtype: object

In [42]:
df.Symbol = label.fit_transform(df.Symbol)
df.Category = label.fit_transform(df.Category)

In [43]:
df.dtypes

Date                 datetime64[ns]
Open                        float64
High                        float64
Low                         float64
Close                       float64
Adj Close                   float64
Volume                        int64
Symbol                        int32
Category                      int32
Daily_Return                float64
Price_Range                 float64
Volatility                  float64
Cumulative_Return           float64
Average_Price               float64
SMA_50                      float64
SMA_200                     float64
RSI                         float64
MACD12                      float64
MACD26                      float64
MACD9                       float64
RollingVolatility           float64
Daily_volatility            float64
Annual_volatility           float64
dtype: object

In [44]:
x = df.drop(['Close','Date'],axis=1).values
y = df['Close'].values

In [45]:
x

array([[3790.        , 3832.        , 3773.        , ...,    0.        ,
        3811.10009766, 3811.10009766],
       [3811.10009766, 3811.10009766, 3767.25      , ...,    0.        ,
        3783.19995117, 3783.19995117],
       [3767.        , 3771.85009766, 3687.05004883, ...,    0.        ,
        3691.75      , 3691.75      ],
       ...,
       [ 665.75      ,  677.90002441,  664.        , ...,  486.7378026 ,
         672.75      ,  672.75      ],
       [ 677.        ,  684.        ,  675.5       , ...,  419.1542302 ,
         678.90002441,  678.90002441],
       [ 681.        ,  683.        ,  674.04998779, ...,  342.399928  ,
         680.5       ,  680.5       ]])

In [46]:
y

array([3811.10009766, 3783.19995117, 3691.75      , ...,  672.75      ,
        678.90002441,  680.5       ])

In [47]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2 , random_state=42)

In [48]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [49]:
model.fit(xtrain,ytrain)

LinearRegression()

In [50]:
ypred = model.predict(xtest)
ypred

array([4479.25      , 2908.30004883, 6061.10009766, ...,  660.95001221,
        309.70001221, 1660.90002441])

In [51]:
from sklearn.metrics import r2_score
r2 = r2_score(ytest,ypred)
r2

1.0

In [52]:
from sklearn.ensemble import RandomForestRegressor
modell = RandomForestRegressor()

In [53]:
modell.fit(xtrain,ytrain)

RandomForestRegressor()

In [54]:
ypred_RFR = modell.predict(xtest)
ypred_RFR

array([4479.3775    , 2907.4089502 , 6057.85599121, ...,  660.83149597,
        309.76950134, 1660.64901001])

In [55]:
from sklearn.metrics import r2_score
r21 = r2_score(ytest,ypred_RFR)
r21

0.9999943386372672

In [56]:
import xgboost as xgb

In [57]:
modelll = xgb.XGBRegressor()

In [58]:
modelll.fit(xtrain,ytrain)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [59]:
ypred_xgb = modell.predict(xtest)
ypred_xgb

array([4479.3775    , 2907.4089502 , 6057.85599121, ...,  660.83149597,
        309.76950134, 1660.64901001])

In [60]:
from sklearn.metrics import r2_score
r211 = r2_score(ytest,ypred_RFR)
r211

0.9999943386372672

In [61]:
df.to_csv('ML_project.csv')